@startuml

!includeurl https://gist.githubusercontent.com/Arnaud-Bonneuil/c317a7a30bed7d64e2b5b1f558ac00cf/raw/sober.puml

title  Dequeue item : queue is empty

actor "Class" as Actor_Class
participant Software_Element as SWE

Actor_Class -> SWE : Dequeue item
Actor_Class <- SWE : No item

@enduml